# Generated by Django 6.0.6 on 2026-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_fix_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='signup_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='signup_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='signup_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
