# Generated by Django 5.2.16 on 2026-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_signup_fields_to_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedContactProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Trusted Contact',
                'verbose_name_plural': 'Trusted Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.emergencycontact',),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
