# Generated by Django 5.2.16 on 2026-08-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_emailotp_id_alter_emergencycontact_id_and_more'),
        ('authentication', '0007_add_signup_fields_to_otp'),
    ]

    operations = [
    ]
