# Generated by Django 5.2.16 on 2026-08-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_merge_20260802_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedContactProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Trusted Contact',
                'verbose_name_plural': 'Trusted Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.emergencycontact',),
        ),
    ]
