# Generated by Django 5.2.16 on 2026-08-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_trustedcontactproxy_alter_emailotp_id_and_more'),
        ('authentication', '0009_trustedcontactproxy'),
    ]

    operations = [
    ]
