# Generated by Django 5.2.16 on 2026-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_unsafereport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsafereport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
