# Generated by Django 6.0.6 on 2026-08-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_unsafereport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsafereport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
