# Generated by Django 5.2.16 on 2026-08-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_emailotp_id_alter_emergencycontact_id_and_more'),
        ('reports', '0005_alter_unsafereport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsafereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unsafe_reports', to='authentication.userprofile'),
        ),
    ]
