# Generated by Django 6.0.6 on 2026-07-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_alter_journey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
