# Generated by Django 5.2.16 on 2026-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_alter_journey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
