# Generated by Codex on 2026-08-04
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_merge_20260804_1139"),
        ("journey", "0004_alter_journey_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="estimated_arrival_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="expected_duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="last_safety_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="missed_check_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="journey",
            name="next_safety_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="safety_check_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="journey",
            name="safety_check_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journey",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="journeys", to="authentication.userprofile"),
        ),
    ]
