# Generated by Django 6.0.6 on 2026-08-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_journey_safety_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
