# Generated by Django 6.0.5 on 2026-06-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_emergencycontact_delete_journey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
