# Generated by Django 6.0.5 on 2026-06-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Triggered', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
