# Generated by Django 6.0.5 on 2026-06-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_emergencycontact_journey_unsafereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
        migrations.DeleteModel(
            name='UnsafeReport',
        ),
    ]
