# Generated by Django 5.2.16 on 2026-07-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sosalert_latitude_sosalert_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
