# Generated by Django 5.2.16 on 2026-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_sosalert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
