# Generated by Django 5.2.16 on 2026-08-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_trustedcontactproxy_alter_emailotp_id_and_more'),
        ('dashboard', '0007_alter_sosalert_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('initial_latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_location', models.TextField(blank=True, null=True)),
                ('last_known_location', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_sessions', to='authentication.userprofile')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SOSPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sos/photos/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dashboard.sossession')),
            ],
        ),
        migrations.CreateModel(
            name='SOSLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('location_name', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='dashboard.sossession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SOSAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='sos/audio/')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='dashboard.sossession')),
            ],
        ),
        migrations.CreateModel(
            name='SOSVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='sos/video/')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.sossession')),
            ],
        ),
    ]
