# Generated by Django 5.2.16 on 2026-08-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sossession_sosphoto_soslocation_sosaudio_sosvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sossession',
            name='nearest_station_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sossession',
            name='nearest_station_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sossession',
            name='nearest_station_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sossession',
            name='nearest_station_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sossession',
            name='nearest_station_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
