# Generated by Django 4.2.30 on 2026-08-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_sossession_nearest_station_distance_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sossession',
            name='nearest_station_distance_km',
        ),
        migrations.RemoveField(
            model_name='sossession',
            name='nearest_station_email',
        ),
        migrations.RemoveField(
            model_name='sossession',
            name='nearest_station_name',
        ),
        migrations.RemoveField(
            model_name='sossession',
            name='nearest_station_phone',
        ),
        migrations.RemoveField(
            model_name='sossession',
            name='nearest_station_type',
        ),
    ]
