# Generated by Django 6.0.5 on 2026-06-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
    ]
